### ISSUE TITLE
Int to string conversion in even_ended challenge

### ISSUE THREAD

**Issue by kartikra** [LinkedInLearning/go-essential-training-2446262#1]
Sprintf seems to be very slow when casting int to string. Recommend strconv.itoa instead

`s := fmt.Sprintf("%d", n)`
go run essentials/even_ended.go  3.93s user 0.20s system 102% cpu 4.027 total

`s := strconv.Itoa(n)`
go run essentials/even_ended.go  1.45s user 0.17s system 102% cpu 1.589 total

**Comment by tebeka** [comment]
Thanks! I amied for simplicity and not speed :)
